name: Dev Branch Pipeline
on:
  push:
    branches:
      - '*'
      - '!main'
run-name: ${{ github.sha }} | ${{ github.event.head_commit.message }}
jobs:
  call-workflow:
    uses: tejadevsecops/github-reusable-actions/.github/workflows/ci-dev-branch.yml@main
    with:
      componentName: user